spring:
  application:
      name: cloud-service-provider
  datasource:
    url: jdbc:mysql://104.224.163.143:3306/yanggy
    #    url: jdbc:mysql://localhost:8066/TESTDB
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    type: com.alibaba.druid.pool.DruidDataSource

#  cloud:
#      config:
#        uri: http://localhost:8888 # config server
#        name: cloud-config # 要读取的配置文件application属性
#        profile: ${config.profile:dev} # default config profile
server:
  port: 1992
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.101:1988/eureka/

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
mybatis:
  mapper-locations: sql-mapper/*.xml