spring:
  application:
      name: cloud-service-provider
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/derrick
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:sql-mapper/*.xml
server:
  port: 1992
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.101:1988/eureka/