spring:
  application:
      name: cloud-service-provider
  datasource:
    url: jdbc:mysql://localhost:3306/yanggy
    driver-class-name: com.mysql.jdbc.Driver
    username: yanggy
    password: ygy250725
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:sql-mapper/*.xml
server:
  port: 1992
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1988/eureka/