spring:
  application:
      name: cloud-service-provider
  cloud:
      config:
        uri: localhost:8888 # config server
        name: cloud-config # 要读取的配置文件application属性
        profile: ${config.profile:dev} # default config profile
server:
  port: 1992
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1988/eureka/

security:
  basic:
    enabled: false
management:
  security:
    enabled: false